<?php
/**
 * Copyright 2013 Zendesk.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<script type="text/javascript">
    function checkApiConnection() {
        var request = new Ajax.Request('<?php echo $this->getTestUrl(); ?>', {
            method: 'get',
            requestHeaders: {
                Authorization: '<?php echo $this->getAuthHeader(); ?>'
            },
            onCreate: function() {
                document.getElementById('zendesk-test-connection-results').innerHTML = '';
            },
            onSuccess: function(transport) {
                var message = '<ul class="messages"><li class="success-msg"><?php echo Mage::helper('zendesk')->__('API test connection successful'); ?></li></ul>';
                document.getElementById('zendesk-test-connection-results').innerHTML = message;
            },
            onFailure: function(transport) {
                var message = '<ul class="messages"><li class="error-msg"><?php echo Mage::helper('zendesk')->__('API test connection failed'); ?><br />' +
                              '<?php echo Mage::helper('zendesk')->__('Troubleshooting tips can be found at <a href="%s" target="_blank">%s</a>', 'https://support.zendesk.com/entries/26579987', 'https://support.zendesk.com/entries/26579987'); ?>' +
                              '</li></ul>';
                document.getElementById('zendesk-test-connection-results').innerHTML = message;
            }
        });
    }
</script>
<button style="" onclick="javascript:checkApiConnection(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
<div id="zendesk-test-connection-results"></div>
