<?php
/**
 * Zendesk Magento integration
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to The MIT License (MIT) that is bundled with
 * this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @copyright Copyright (c) 2012 Zendesk (www.zendesk.com)
 * @license http://opensource.org/licenses/mit-license.php The MIT License (MIT)
 */
?>
<script type="text/javascript">
    function postToZendesk() {
        var form = new Element('form', {method: 'post', action: '<?php echo $this->getPostUrl(); ?>'});
        <?php foreach($this->getPostInfo() as $name => $value): ?>
            form.insert(new Element('input', {type: 'hidden', name: '<?php echo $name; ?>', value: '<?php echo $value; ?>'}));
        <?php endforeach; ?>
        $(document.body).insert(form);
        form.submit();
    }
</script>
<button style="" onclick="javascript:postToZendesk(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
