<?php
/**
 * Copyright 2012 Zendesk.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<script type="text/javascript">
    function postToZendesk() {
        var form = new Element('form', {method: 'post', action: '<?php echo $this->getPostUrl(); ?>'});
        <?php foreach($this->getPostInfo() as $name => $value): ?>
            form.insert(new Element('input', {type: 'hidden', name: '<?php echo $name; ?>', value: '<?php echo $value; ?>'}));
        <?php endforeach; ?>
        $(document.body).insert(form);
        form.submit();
    }
</script>
<button style="" onclick="javascript:postToZendesk(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
