<?php
/**
 * Copyright 2015 Zendesk.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<select id="zendesk_features_feedback_tab_code_active" name="groups[features][fields][feedback_tab_code_active][value]" class=" select" onChange="processFeedbackChange(this);return false;">
  <option value="1" <?php if($this->feedbackTabActive) echo 'selected="selected"'; ?>>Yes</option>
  <option value="0" <?php if(!$this->feedbackTabActive) echo 'selected="selected"'; ?>>No</option>
</select>
<script language="javascript">
  function processFeedbackChange(toggle) {
    document.getElementById("feedback_tab_hidden").value = (toggle.value === '0');
  }
</script>
<input type="hidden" name="groups[features][fields][feedback_tab_hidden][value]" id="feedback_tab_hidden" value="0" />