<?php
/**
 * Copyright 2014 Zendesk.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>

<?php
    if(!Mage::getStoreConfig('zendesk/frontend_features/customer_tickets')) {
        return;
    }
?>

<div>
    <div class="page-title">
        <h1><?php echo $this->__('My Tickets') ?></h1>
    </div>

    <div><?php echo $this->getChildHtml(); ?></div>
</div>
<div class="buttons-set">
    <a class="button" target="_blank" href="<?php echo $this->getSubmitAction() ?>"><span><span><?php echo $this->__('Open Ticket') ?></span></span></a>
    <a class="button" target="_blank" href="<?php echo Mage::helper('zendesk')->getSSOAuthUrlEndUsers(); ?>"><span><span><?php echo $this->__('Log In To Zendesk') ?></span></span></a>
</div>
