<?php
/**
 * Copyright 2013 Zendesk.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<div class="content-header">
    <h3 class="icon-head head-empty"><?php echo $this->__('Log Viewer') ?></h3>
    <p class="form-buttons">
        <button id="download-log" title="Download" type="button" class="scalable" onclick="setLocation('<?php echo $this->getUrl('adminhtml/zendesk/download'); ?>');">
            <span>Download Log</span>
        </button>
        <button id="clear-log" title="Clear Log" type="button" class="scalable delete" onclick="confirmSetLocation('<?php echo $this->__('Are you sure you want to clear the entire Zendesk log?'); ?>', '<?php echo $this->getUrl('adminhtml/zendesk/clearLog'); ?>');">
            <span>Clear Log</span>
        </button>
    </p>
</div>
<div class="zendesk_log_container">
    <textarea style="width: 100%; height: 400px;"><?php echo $this->getLogContents(); ?></textarea>
</div>