<?php

/* * ********************************************************************
 * Customization Services by ModulesGarden.com
 * Copyright (c) ModulesGarden, INBS Group Brand, All Rights Reserved 
 * (2014-05-16, 12:17:41)
 * 
 *
 *  CREATED BY MODULESGARDEN       ->        http://modulesgarden.com
 *  CONTACT                        ->       contact@modulesgarden.com
 *
 *
 *
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software  or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and  ownership of the  software is  hereby
 * transferred.
 *
 *
 * ******************************************************************** */

/**
 * @author Grzegorz Draganik <grzegorz@modulesgarden.com>
 */
?>

<div class="modulesgarden_form_container">
	<?php echo $this->getFormInitScripts() ?>
	<div class="content-header <?php echo $this->getSkipHeaderCopy() ? 'skip-header' : ''; ?>">
		<?php echo $this->getHeaderHtml() ?>
		<p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
	</div>
    
        <?php if($this->hasMessage()): ?>
        <div id="messages">
            <ul class="messages">
                <li class="notice-msg"><?php echo $this->getMessage() ?></li>
            </ul>
        </div>
        <?php endif ?>
        
	<?php echo $this->getFormHtml() ?>
	<?php if ($this->hasFooterButtons()): ?>
		<div class="content-footer">
			<p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
		</div>
	<?php endif; ?>
	<script type="text/javascript">
		editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
	</script>
	<?php echo $this->getFormScripts() ?>
</div>
