<?php
/**
 * Copyright 2015 Zendesk
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>

<div class="modulesgarden_form_container">
	<?php echo $this->getFormInitScripts() ?>
	<div class="content-header <?php echo $this->getSkipHeaderCopy() ? 'skip-header' : ''; ?>">
		<?php echo $this->getHeaderHtml() ?>
		<p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
	</div>
    
        <?php if($this->hasMessage()): ?>
        <div id="messages">
            <ul class="messages">
                <li class="notice-msg"><?php echo $this->getMessage() ?></li>
            </ul>
        </div>
        <?php endif ?>
        
	<?php echo $this->getFormHtml() ?>
	<?php if ($this->hasFooterButtons()): ?>
		<div class="content-footer">
			<p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
		</div>
	<?php endif; ?>
	<script type="text/javascript">
		editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
	</script>
	<?php echo $this->getFormScripts() ?>
</div>
